metadata:
  directory: $HOME/experiment
  name: "test"
runs:
  run_0:
    sbatch:
      mem: 16G
      runtime: "1:00:00"
    data:
      path: $SCRATCH/data/glaciers/processed/
      subset: 10
    train:
      model:
        name: Unet
        args:
          inchannels: 3
          outchannels: 1
          net_depth: 2
      optim:
        name: Adam
        args:
          lr: 1e-6
      metrics:
        precision:
          threshold: 0.2
        IoU:
          threshold: 0.4
      loop:
        train_batch_size: 5
        val_batch_size: 15
        epochs: 20
  run_1:
    sbatch:
      mem: 16G
      runtime: "1:00:00"
    data:
      path: $SCRATCH/data/glaciers/processed/
      subset: 10
    train:
      model:
        name: Unet
        args:
          inchannels: 3
          outchannels: 1
          net_depth: 2
      optim:
        name: Adam
        args:
          lr: 1e-6
      metrics:
        precision:
          threshold: 0.2
        IoU:
          threshold: 0.4
      loop:
        train_batch_size: 5
        val_batch_size: 15
        epochs: 20
