metadata:
  directory: $HOME/experiment
  name: "sweep1"
runs:
  run_0:
    sbatch: {}
    data:
      path: $SCRATCH/data/glaciers/processed/
      subset: 10
    train:
      optim:
        args:
          lr: 1e-6