metadata:
  directory: $HOME/experiment
  name: "sweep2"
runs:
  run_0:
    sbatch: {}
    data:
      path: /scratch/akera/data/glaciers/processed/
      subset: 10
    train:
      optim:
        name: Adam
        args:
          lr: 0.000001
  run_2:
    sbatch: {}
    data:
      path: /scratch/akera/data/glaciers/processed/
      subset: 10
    train:
      optim:
        name: Adam
        args:
          lr: 0.001
  run_3:
    sbatch: {}
    data:
      path: /scratch/akera/data/glaciers/processed/
      subset: 10
    train:
      optim:
        name: Adam
        args:
          lr: 0.00000001
  run_4:
    sbatch: {}
    data:
      path: /scratch/akera/data/glaciers/processed/
      subset: 10
    train:
      optim:
        name: Adam
        args:
          lr: 0.01
