model:
  name: Unet
  args:
    inchannels: 3
    outchannels: 1
    net_depth: 2
optim:
  name: Adam
  args:
    lr: 0.0001
metrics:
  precision:
    threshold: 0.0
  IoU:
    threshold: 0.0
loop:
  train_batch_size: 5
  val_batch_size: 15
  epochs: 20
